version: 2.1

orbs:
  docker: circleci/docker@2.8.2

executors:
  vm-executor:
    machine: true
    working_directory: ~/app

jobs:
  build-and-push:
    executor: vm-executor
    steps:
      - checkout

      - docker/check:
          docker-username: DOCKERHUB_USERNAME
          docker-password: DOCKERHUB_TOKEN

      - docker/build:
          image: $DOCKERHUB_USERNAME/my-node-app
          tag: latest

      - docker/push:
          image: $DOCKERHUB_USERNAME/my-node-app
          tag: latest

workflows:
  version: 2
  build_and_push:
    jobs:
      - build-and-push
